"""add func type

Revision ID: 00b9fe07270b
Revises: 9eb4b207d283
Create Date: 2024-10-09 14:24:33.289611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b9fe07270b'
down_revision: Union[str, None] = '9eb4b207d283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skillsets', sa.Column('function_type', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_skillsets_function_type'), 'skillsets', ['function_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skillsets_function_type'), table_name='skillsets')
    op.drop_column('skillsets', 'function_type')
    # ### end Alembic commands ###
