"""add skill name to ce

Revision ID: 0f311385b308
Revises: 727760d9429a
Create Date: 2024-10-09 16:19:03.755271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f311385b308'
down_revision: Union[str, None] = '727760d9429a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craft_essence_skills', sa.Column('skill_name', sa.String(length=255), nullable=True, comment='技能名'))
    op.add_column('craft_essence_skills', sa.Column('skill_type', sa.String(length=255), nullable=True, comment='技能类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('craft_essence_skills', 'skill_type')
    op.drop_column('craft_essence_skills', 'skill_name')
    # ### end Alembic commands ###
