"""update tables

Revision ID: 1892c658600b
Revises: 
Create Date: 2024-08-20 16:07:10.337621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1892c658600b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servants',
    sa.Column('servant_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('servant_collection_no', sa.Integer(), nullable=True),
    sa.Column('servant_name', sa.String(length=255), nullable=True),
    sa.Column('servant_name_cn', sa.String(length=255), nullable=True, comment='从者的中文名'),
    sa.Column('servant_class', sa.String(length=255), nullable=True, comment='从者职介'),
    sa.Column('servant_rarity', sa.Integer(), nullable=True, comment='从者的稀有度'),
    sa.Column('np_rate', sa.Float(), nullable=True, comment='NP获取率'),
    sa.Column('attack', sa.Integer(), nullable=True, comment='从者满级的攻击力'),
    sa.Column('hp', sa.Integer(), nullable=True, comment='从者满级的生命值'),
    sa.Column('tendancy', sa.Float(), nullable=True, comment='从者的攻防倾向'),
    sa.Column('class_tendancy', sa.Float(), nullable=True, comment='从者职介的倾向'),
    sa.Column('star_absorb_rate', sa.Integer(), nullable=True, comment='暴击星集中度'),
    sa.Column('related_cards', sa.String(length=255), nullable=True, comment='从者相关的指令卡,以及-分割，最后一格为宝具卡'),
    sa.Column('servant_card_hits', sa.String(length=255), nullable=True, comment='从者指令卡hitsh数'),
    sa.PrimaryKeyConstraint('servant_id')
    )
    op.create_index(op.f('ix_servants_related_cards'), 'servants', ['related_cards'], unique=False)
    op.create_index(op.f('ix_servants_servant_class'), 'servants', ['servant_class'], unique=False)
    op.create_index(op.f('ix_servants_servant_collection_no'), 'servants', ['servant_collection_no'], unique=False)
    op.create_index(op.f('ix_servants_servant_rarity'), 'servants', ['servant_rarity'], unique=False)
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=True),
    sa.Column('skill_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_skill_type'), 'skills', ['skill_type'], unique=False)
    op.create_table('buff_function_mapping',
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('buff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buff_id'], ['buffs.buff_id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.function_id'], )
    )
    op.create_table('ce_skill_mapping',
    sa.Column('ce_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ce_id'], ['craft_essences.ce_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], )
    )
    op.create_table('noble_phantasm_mapping',
    sa.Column('noble_phantasm_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noble_phantasm_id'], ['noble_phantasms.noble_phantasm_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], )
    )
    op.create_table('servant_skill_mapping',
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servant_id'], ['servants.servant_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], )
    )
    op.create_table('skill_function_mapping',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['functions.function_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], )
    )
    op.create_table('skillsets',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_name_cn', sa.String(length=255), nullable=True, comment='中文名'),
    sa.Column('skill_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('auxiliary_skill_id', sa.Integer(), nullable=True, comment='dummy skill 的id'),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('skill_type', sa.String(length=255), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('buff_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=False, comment='同一类buff多次叠加'),
    sa.Column('max_cooldown', sa.Integer(), nullable=True),
    sa.Column('strength_status', sa.Integer(), nullable=True, comment='技能强化状态'),
    sa.ForeignKeyConstraint(['function_id'], ['functions.function_id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'skill_id', 'function_id', 'buff_id', 'idx')
    )
    op.create_index(op.f('ix_skillsets_count'), 'skillsets', ['count'], unique=False)
    op.create_index(op.f('ix_skillsets_idx'), 'skillsets', ['idx'], unique=False)
    op.create_index(op.f('ix_skillsets_max_cooldown'), 'skillsets', ['max_cooldown'], unique=False)
    op.create_index(op.f('ix_skillsets_skill_type'), 'skillsets', ['skill_type'], unique=False)
    op.create_index(op.f('ix_skillsets_strength_status'), 'skillsets', ['strength_status'], unique=False)
    op.create_index(op.f('ix_skillsets_turn'), 'skillsets', ['turn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skillsets_turn'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_strength_status'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_skill_type'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_max_cooldown'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_idx'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_count'), table_name='skillsets')
    op.drop_table('skillsets')
    op.drop_table('skill_function_mapping')
    op.drop_table('servant_skill_mapping')
    op.drop_table('noble_phantasm_mapping')
    op.drop_table('ce_skill_mapping')
    op.drop_table('buff_function_mapping')
    op.drop_index(op.f('ix_skills_skill_type'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_servants_servant_rarity'), table_name='servants')
    op.drop_index(op.f('ix_servants_servant_collection_no'), table_name='servants')
    op.drop_index(op.f('ix_servants_servant_class'), table_name='servants')
    op.drop_index(op.f('ix_servants_related_cards'), table_name='servants')
    op.drop_table('servants')
    # ### end Alembic commands ###
