"""chaneg auxiliary skill id type

Revision ID: 1f2f290d678e
Revises: 6e0a1cba437f
Create Date: 2024-08-21 17:32:25.790236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f2f290d678e'
down_revision: Union[str, None] = '6e0a1cba437f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skillsets', 'auxiliary_skill_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_comment='dummy skill 的id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skillsets', 'auxiliary_skill_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_comment='dummy skill 的id',
               existing_nullable=True)
    # ### end Alembic commands ###
