"""add servant cards

Revision ID: 2df60c35a6c7
Revises: 1892c658600b
Create Date: 2024-08-21 11:24:35.604644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2df60c35a6c7'
down_revision: Union[str, None] = '1892c658600b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servant_cards',
    sa.Column('card_id', sa.String(length=255), nullable=False),
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.String(length=255), nullable=True),
    sa.Column('card_np', sa.Integer(), nullable=True, comment='指令卡的 NP值'),
    sa.Column('card_hits', sa.Integer(), nullable=True, comment='指令卡的 hit 数'),
    sa.Column('card_dist', sa.String(length=255), nullable=True, comment='指令卡的 hit'),
    sa.Column('card_dist_acc', sa.String(length=255), nullable=True, comment='指令卡累计hit比率'),
    sa.ForeignKeyConstraint(['servant_id'], ['servants.servant_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_servant_cards_card_type'), 'servant_cards', ['card_type'], unique=False)
    op.drop_index('ix_servants_related_cards', table_name='servants')
    op.drop_column('servants', 'servant_card_hits')
    op.drop_column('servants', 'related_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servants', sa.Column('related_cards', mysql.VARCHAR(length=255), nullable=True, comment='从者相关的指令卡,以及-分割，最后一格为宝具卡'))
    op.add_column('servants', sa.Column('servant_card_hits', mysql.VARCHAR(length=255), nullable=True, comment='从者指令卡hitsh数'))
    op.create_index('ix_servants_related_cards', 'servants', ['related_cards'], unique=False)
    op.drop_index(op.f('ix_servant_cards_card_type'), table_name='servant_cards')
    op.drop_table('servant_cards')
    # ### end Alembic commands ###
