"""add self trait to buff

Revision ID: 4fb2aba74830
Revises: 515996f8438e
Create Date: 2024-08-22 16:26:12.564870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb2aba74830'
down_revision: Union[str, None] = '515996f8438e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buffs', sa.Column('related_self_trait', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_buffs_related_self_trait'), 'buffs', ['related_self_trait'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buffs_related_self_trait'), table_name='buffs')
    op.drop_column('buffs', 'related_self_trait')
    # ### end Alembic commands ###
