"""add individuality check to buff

Revision ID: 513ea0e8c45e
Revises: 4fb2aba74830
Create Date: 2024-08-22 16:57:51.299269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513ea0e8c45e'
down_revision: Union[str, None] = '4fb2aba74830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buffs', sa.Column('related_individuality', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_buffs_related_individuality'), 'buffs', ['related_individuality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buffs_related_individuality'), table_name='buffs')
    op.drop_column('buffs', 'related_individuality')
    # ### end Alembic commands ###
