"""increase trait length

Revision ID: 515996f8438e
Revises: 93619617d2ed
Create Date: 2024-08-22 12:16:53.229893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '515996f8438e'
down_revision: Union[str, None] = '93619617d2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servants', 'traits',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_comment='从者的特性',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servants', 'traits',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_comment='从者的特性',
               existing_nullable=True)
    # ### end Alembic commands ###
