"""changes to servants

Revision ID: 543713c66d3d
Revises: 2df60c35a6c7
Create Date: 2024-08-21 15:58:33.723593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '543713c66d3d'
down_revision: Union[str, None] = '2df60c35a6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_functions_related_quest_trait', table_name='functions')
    op.drop_index('ix_functions_related_target_trait', table_name='functions')
    op.drop_column('functions', 'related_quest_trait')
    op.drop_column('functions', 'related_target_trait')
    op.add_column('servants', sa.Column('star_gen_rate', sa.Integer(), nullable=True, comment='星集中度'))
    op.add_column('skillsets', sa.Column('skill_no', sa.Integer(), nullable=True))
    op.add_column('skillsets', sa.Column('skill_priority', sa.Integer(), nullable=True))
    op.add_column('skillsets', sa.Column('userate', sa.Float(), nullable=True, comment='触发新的技能的概率'))
    op.alter_column('skillsets', 'value',
               existing_type=mysql.FLOAT(),
               comment='技能效果的具体数值,dummy skill 会直接展开',
               existing_nullable=True)
    op.create_index(op.f('ix_skillsets_skill_no'), 'skillsets', ['skill_no'], unique=False)
    op.create_index(op.f('ix_skillsets_skill_priority'), 'skillsets', ['skill_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skillsets_skill_priority'), table_name='skillsets')
    op.drop_index(op.f('ix_skillsets_skill_no'), table_name='skillsets')
    op.alter_column('skillsets', 'value',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='技能效果的具体数值,dummy skill 会直接展开',
               existing_nullable=True)
    op.drop_column('skillsets', 'userate')
    op.drop_column('skillsets', 'skill_priority')
    op.drop_column('skillsets', 'skill_no')
    op.drop_column('servants', 'star_gen_rate')
    op.add_column('functions', sa.Column('related_target_trait', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('functions', sa.Column('related_quest_trait', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_functions_related_target_trait', 'functions', ['related_target_trait'], unique=False)
    op.create_index('ix_functions_related_quest_trait', 'functions', ['related_quest_trait'], unique=False)
    # ### end Alembic commands ###
