"""add skill name as pkey

Revision ID: 574169d7d7cb
Revises: 00b9fe07270b
Create Date: 2024-10-09 15:59:48.743295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574169d7d7cb'
down_revision: Union[str, None] = '00b9fe07270b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
