"""add quest traits to functions

Revision ID: 6e0a1cba437f
Revises: ac3421b430e9
Create Date: 2024-08-21 17:14:16.597879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0a1cba437f'
down_revision: Union[str, None] = 'ac3421b430e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('function_quest_vals', sa.String(length=255), nullable=True))
    op.add_column('skillsets', sa.Column('function_quest_traits', sa.String(length=255), nullable=True, comment='Quest Traits'))
    op.add_column('skillsets', sa.Column('function_target_traits', sa.String(length=255), nullable=True, comment='技能的目标特性'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skillsets', 'function_target_traits')
    op.drop_column('skillsets', 'function_quest_traits')
    op.drop_column('functions', 'function_quest_vals')
    # ### end Alembic commands ###
