"""add buff fields

Revision ID: 7a22552e0c15
Revises: a8e3b68a0126
Create Date: 2024-10-09 16:22:45.355101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a22552e0c15'
down_revision: Union[str, None] = 'a8e3b68a0126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craft_essence_skills', sa.Column('buff_check', sa.String(length=255), nullable=True, comment='Buff检查'))
    op.add_column('craft_essence_skills', sa.Column('buff_target_traits', sa.String(length=255), nullable=True, comment='Buff的目标特性'))
    op.alter_column('craft_essence_skills', 'buff_release_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_craft_essence_skills_buff_type'), 'craft_essence_skills', ['buff_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craft_essence_skills_buff_type'), table_name='craft_essence_skills')
    op.alter_column('craft_essence_skills', 'buff_release_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('craft_essence_skills', 'buff_target_traits')
    op.drop_column('craft_essence_skills', 'buff_check')
    # ### end Alembic commands ###
