"""add np card type

Revision ID: 9df5f40cc394
Revises: 3129436507ab
Create Date: 2024-09-11 12:02:22.025522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df5f40cc394'
down_revision: Union[str, None] = '3129436507ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noble_phantasms', sa.Column('card_type', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_noble_phantasms_card_type'), 'noble_phantasms', ['card_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noble_phantasms_card_type'), table_name='noble_phantasms')
    op.drop_column('noble_phantasms', 'card_type')
    # ### end Alembic commands ###
