"""add function target type to ce

Revision ID: a8e3b68a0126
Revises: 0f311385b308
Create Date: 2024-10-09 16:21:12.627770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e3b68a0126'
down_revision: Union[str, None] = '0f311385b308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craft_essence_skills', sa.Column('function_target_type', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_craft_essence_skills_function_target_type'), 'craft_essence_skills', ['function_target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craft_essence_skills_function_target_type'), table_name='craft_essence_skills')
    op.drop_column('craft_essence_skills', 'function_target_type')
    # ### end Alembic commands ###
