"""add CraftEssenceSkill

Revision ID: abfa4d9d2b4e
Revises: 513ea0e8c45e
Create Date: 2024-09-11 10:24:00.761645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfa4d9d2b4e'
down_revision: Union[str, None] = '513ea0e8c45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_essence_skills',
    sa.Column('ce_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ce_name', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('auxiliary_skill_id', sa.String(length=255), nullable=True),
    sa.Column('function_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('function_quest_traits', sa.String(length=255), nullable=True),
    sa.Column('function_target_traits', sa.String(length=255), nullable=True),
    sa.Column('strength_status', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('buff_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('userate', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ce_id', 'ce_name', 'skill_id', 'function_id', 'strength_status', 'buff_id', 'idx')
    )
    op.add_column('craft_essences', sa.Column('ce_name_cn', sa.String(length=255), nullable=True, comment='中文名'))
    op.add_column('craft_essences', sa.Column('max_atk', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_craft_essences_max_atk'), 'craft_essences', ['max_atk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craft_essences_max_atk'), table_name='craft_essences')
    op.drop_column('craft_essences', 'max_atk')
    op.drop_column('craft_essences', 'ce_name_cn')
    op.drop_table('craft_essence_skills')
    # ### end Alembic commands ###
