"""remove fields from np

Revision ID: ac3421b430e9
Revises: 543713c66d3d
Create Date: 2024-08-21 16:11:01.888524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac3421b430e9'
down_revision: Union[str, None] = '543713c66d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_noble_phantasms_card_type', table_name='noble_phantasms')
    op.drop_index('ix_noble_phantasms_hitsDist', table_name='noble_phantasms')
    op.drop_column('noble_phantasms', 'card_type')
    op.drop_column('noble_phantasms', 'hits')
    op.drop_column('noble_phantasms', 'np_gain')
    op.drop_column('noble_phantasms', 'hitsDist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noble_phantasms', sa.Column('hitsDist', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('noble_phantasms', sa.Column('np_gain', mysql.INTEGER(), autoincrement=False, nullable=True, comment='宝具 NP值'))
    op.add_column('noble_phantasms', sa.Column('hits', mysql.INTEGER(), autoincrement=False, nullable=True, comment='从者满级的命中'))
    op.add_column('noble_phantasms', sa.Column('card_type', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_noble_phantasms_hitsDist', 'noble_phantasms', ['hitsDist'], unique=False)
    op.create_index('ix_noble_phantasms_card_type', 'noble_phantasms', ['card_type'], unique=False)
    # ### end Alembic commands ###
