"""add CraftEssenceSkill buff id default

Revision ID: b033d5c37482
Revises: abfa4d9d2b4e
Create Date: 2024-09-11 10:36:08.274201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033d5c37482'
down_revision: Union[str, None] = 'abfa4d9d2b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
