"""add rebuild

Revision ID: cc821ef8c5c0
Revises: 
Create Date: 2024-10-09 11:19:06.285309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc821ef8c5c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servant_cards',
    sa.Column('card_id', sa.String(length=255), nullable=False),
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.String(length=255), nullable=True),
    sa.Column('card_np', sa.Integer(), nullable=True, comment='指令卡的 NP值'),
    sa.Column('card_hits', sa.Integer(), nullable=True, comment='指令卡的 hit 数'),
    sa.Column('card_dist', sa.String(length=255), nullable=True, comment='指令卡的 hit'),
    sa.Column('card_dist_acc', sa.String(length=255), nullable=True, comment='指令卡累计hit比率'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_servant_cards_card_type'), 'servant_cards', ['card_type'], unique=False)
    op.add_column('servants', sa.Column('id', sa.Integer(), autoincrement=False, nullable=False))
    op.add_column('servants', sa.Column('collection_no', sa.Integer(), nullable=True))
    op.add_column('servants', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('servants', sa.Column('name_cn', sa.String(length=255), nullable=True, comment='从者的中文名'))
    op.add_column('servants', sa.Column('class_name', sa.String(length=255), nullable=True, comment='从者职介'))
    op.add_column('servants', sa.Column('rarity', sa.Integer(), nullable=True, comment='从者的稀有度'))
    op.add_column('servants', sa.Column('star_gen_rate', sa.Integer(), nullable=True, comment='星集中度'))
    op.add_column('servants', sa.Column('class_mod', sa.Integer(), nullable=True, comment='职介系数'))
    op.add_column('servants', sa.Column('attribute', sa.String(length=255), nullable=True, comment='从者阵营'))
    op.add_column('servants', sa.Column('traits', sa.String(length=1000), nullable=True, comment='从者的特性'))
    op.drop_index('ix_servants_related_cards', table_name='servants')
    op.drop_index('ix_servants_servant_class', table_name='servants')
    op.drop_index('ix_servants_servant_collection_no', table_name='servants')
    op.drop_index('ix_servants_servant_rarity', table_name='servants')
    op.create_index(op.f('ix_servants_class_name'), 'servants', ['class_name'], unique=False)
    op.create_index(op.f('ix_servants_collection_no'), 'servants', ['collection_no'], unique=False)
    op.create_index(op.f('ix_servants_rarity'), 'servants', ['rarity'], unique=False)
    op.drop_column('servants', 'servant_collection_no')
    op.drop_column('servants', 'servant_rarity')
    op.drop_column('servants', 'servant_name')
    op.drop_column('servants', 'related_cards')
    op.drop_column('servants', 'servant_class')
    op.drop_column('servants', 'servant_name_cn')
    op.drop_column('servants', 'class_tendancy')
    op.drop_column('servants', 'servant_card_hits')
    op.drop_column('servants', 'servant_id')
    op.drop_column('servants', 'np_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servants', sa.Column('np_rate', mysql.FLOAT(), nullable=True, comment='NP获取率'))
    op.add_column('servants', sa.Column('servant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('servants', sa.Column('servant_card_hits', mysql.VARCHAR(length=255), nullable=True, comment='从者指令卡hitsh数'))
    op.add_column('servants', sa.Column('class_tendancy', mysql.FLOAT(), nullable=True, comment='从者职介的倾向'))
    op.add_column('servants', sa.Column('servant_name_cn', mysql.VARCHAR(length=255), nullable=True, comment='从者的中文名'))
    op.add_column('servants', sa.Column('servant_class', mysql.VARCHAR(length=255), nullable=True, comment='从者职介'))
    op.add_column('servants', sa.Column('related_cards', mysql.VARCHAR(length=255), nullable=True, comment='从者相关的指令卡,以及-分割，最后一格为宝具卡'))
    op.add_column('servants', sa.Column('servant_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('servants', sa.Column('servant_rarity', mysql.INTEGER(), autoincrement=False, nullable=True, comment='从者的稀有度'))
    op.add_column('servants', sa.Column('servant_collection_no', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_servants_rarity'), table_name='servants')
    op.drop_index(op.f('ix_servants_collection_no'), table_name='servants')
    op.drop_index(op.f('ix_servants_class_name'), table_name='servants')
    op.create_index('ix_servants_servant_rarity', 'servants', ['servant_rarity'], unique=False)
    op.create_index('ix_servants_servant_collection_no', 'servants', ['servant_collection_no'], unique=False)
    op.create_index('ix_servants_servant_class', 'servants', ['servant_class'], unique=False)
    op.create_index('ix_servants_related_cards', 'servants', ['related_cards'], unique=False)
    op.drop_column('servants', 'traits')
    op.drop_column('servants', 'attribute')
    op.drop_column('servants', 'class_mod')
    op.drop_column('servants', 'star_gen_rate')
    op.drop_column('servants', 'rarity')
    op.drop_column('servants', 'class_name')
    op.drop_column('servants', 'name_cn')
    op.drop_column('servants', 'name')
    op.drop_column('servants', 'collection_no')
    op.drop_column('servants', 'id')
    op.drop_index(op.f('ix_servant_cards_card_type'), table_name='servant_cards')
    op.drop_table('servant_cards')
    # ### end Alembic commands ###
