"""CHANGE CLASS_MODE type

Revision ID: e227a1d377d6
Revises: 27c4a01cacc0
Create Date: 2024-10-09 17:29:47.418348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e227a1d377d6'
down_revision: Union[str, None] = '27c4a01cacc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servants', 'class_mod',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(precision=3),
               existing_comment='职介系数',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servants', 'class_mod',
               existing_type=sa.Float(precision=3),
               type_=mysql.INTEGER(),
               existing_comment='职介系数',
               existing_nullable=True)
    # ### end Alembic commands ###
