"""add func release order for ce

Revision ID: ea947802760a
Revises: fb8e48102a64
Create Date: 2024-10-09 16:32:01.886629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea947802760a'
down_revision: Union[str, None] = 'fb8e48102a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('craft_essence_skills', 'function_release_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('craft_essence_skills', 'function_release_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
