"""remove strength status for ce

Revision ID: fb8e48102a64
Revises: 7a22552e0c15
Create Date: 2024-10-09 16:24:28.788850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb8e48102a64'
down_revision: Union[str, None] = '7a22552e0c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('craft_essence_skills', 'strength_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craft_essence_skills', sa.Column('strength_status', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
